# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_auto_20180512_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.Goods'),
        ),
    ]
